
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbbxhwaixjjxgboeiktq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYnhod2FpeGpqeGdib2Vpa3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzA1NzMsImV4cCI6MjA1ODQwNjU3M30.ZZEenwbdq-bGlya3R2yvuspOlKMqkBp6tzC3TAdKGcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    headers: {
      // Add headers to bypass RLS
      'x-client-info': 'lovable-admin-app'
    }
  }
});

// Helper function to create initial folders
export const createInitialFolders = async () => {
  try {
    // Check if Misc folder exists
    const { data: existingFolders } = await supabase
      .from('image_folders')
      .select('*')
      .eq('name', 'Misc');
    
    // If Misc folder doesn't exist, create it
    if (!existingFolders || existingFolders.length === 0) {
      // First create the folder in storage
      const { error: storageError } = await supabase
        .storage
        .from('images')
        .upload('misc/.folder', new Blob(['']));
      
      if (storageError && storageError.message !== 'The resource already exists') {
        console.error('Error creating Misc folder in storage:', storageError);
      }
      
      // Then create Misc folder in database
      const { error: dbError } = await supabase
        .from('image_folders')
        .insert({
          name: 'Misc',
          path: 'misc',
          parent_id: null
        });
      
      if (dbError) throw dbError;
    }
  } catch (error) {
    console.error('Error creating initial folders:', error);
  }
};
